replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-public-0
    certmanager.k8s.io/cluster-issuer: letsencrypt-development
  path: /
  host: homework.example.com
  tls:
    - secretName: homework-example-com
      hosts:
        - homework.example.com
  labels: {}