apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
  - name: ci-container
    image: python:3.8.5-alpine3.12
    imagePullPolicy: Always
    tty: true
  - name: docker-dind
    image: docker:19.03.12-dind
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  - name: helm
    image: alpine/helm:3.3.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: k8s-kubeconfig
        mountPath: /root/.kube/
        readOnly: true
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: k8s-kubeconfig
      configMap:
        name: k8s-kubeconfig-configmap